const cfg=window.SUPABASE_CONFIG,ad=document.querySelector('#auth-dialog'),sd=document.querySelector('#sheet-dialog');let mode='login',sb,user,token;
const ready=()=>cfg?.url&&cfg?.publishableKey&&!cfg.url.includes('TU-');const note=t=>{let e=document.querySelector('#setup-notice');e.textContent=t;e.classList.remove('hidden')};
function modeSet(m){mode=m;let s=m==='signup';document.querySelector('#auth-kicker').textContent=s?'CREA TU ESPACIO':'BIENVENIDO';document.querySelector('#auth-title').textContent=s?'Crea tu cuenta':'Entra a tu cuenta';document.querySelector('#auth-submit').textContent=s?'Crear cuenta':'Entrar';document.querySelector('#switch-copy').textContent=s?'¿Ya tienes una cuenta?':'¿Aún no tienes cuenta?';document.querySelector('#switch-auth').textContent=s?'Entrar':'Crear cuenta'}
function bind(){document.querySelectorAll('[data-open-auth]').forEach(b=>b.onclick=async()=>{if(!ready())return note('La conexión todavía no está lista.');let {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,scopes:'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.metadata.readonly',queryParams:{access_type:'offline',prompt:'consent'}}});if(error)note(error.message)})}
async function dashboard(u){user=u;document.querySelector('#public-home').classList.add('hidden');document.querySelector('#dashboard').classList.remove('hidden');document.querySelector('#user-name').textContent=u.email.split('@')[0];await projects()}
async function projects(){let {data,error}=await sb.from('projects').select('*').order('created_at',{ascending:false});if(error)return note(error.message);let e=document.querySelector('#project-empty'),g=document.querySelector('#projects-grid');e.classList.toggle('hidden',!!data.length);g.classList.toggle('hidden',!data.length);g.innerHTML=data.map(p=>`<article class="project-card"><p>GOOGLE SHEETS</p><h3>${p.name}</h3><p>${p.sheet_name}</p><div class="project-actions"><button class="action-button" data-read="${p.id}">Ver datos</button><button class="action-button" data-format="${p.id}">Formatear títulos</button></div></article>`).join('');g.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>preview(data.find(p=>p.id===b.dataset.read)));g.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>format(data.find(p=>p.id===b.dataset.format)))}
async function google(){if(token)return token;if(!window.google?.accounts?.oauth2)throw Error('Google está cargando; vuelve a intentarlo.');return new Promise((ok,bad)=>window.google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.metadata.readonly',callback:r=>r.error?bad(Error(r.error)):ok(token=r.access_token)}).requestAccessToken({prompt:'consent'}))}
async function gf(url,opt={}){let r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${await google()}`,'Content-Type':'application/json'}});if(!r.ok)throw Error((await r.json()).error?.message||'Error en Google');return r.json()}
async function sheets(){let m=document.querySelector('#sheet-message'),b=document.querySelector('#authorize-google');b.disabled=true;m.textContent='Buscando tus hojas…';try{let d=await gf("https://www.googleapis.com/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27%20and%20trashed%3Dfalse&fields=files(id%2Cname)&pageSize=50");document.querySelector('#sheets-list').innerHTML=(d.files||[]).map(f=>`<button class="sheet-option" data-id="${f.id}" data-name="${f.name}">▦ ${f.name}</button>`).join('');document.querySelectorAll('.sheet-option').forEach(x=>x.onclick=()=>add(x.dataset.id,x.dataset.name));b.classList.add('hidden')}catch(e){m.textContent=e.message;b.disabled=false}}
async function add(id,name){try{let d=await gf(`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=sheets.properties`),sheet=d.sheets[0].properties.title,{error}=await sb.from('projects').insert({user_id:user.id,name,spreadsheet_id:id,sheet_name:sheet});if(error)throw error;sd.close();note('Proyecto conectado. Ya puedes consultar y formatear.');projects()}catch(e){document.querySelector('#sheet-message').textContent=e.message}}
async function preview(p){try{let d=await gf(`https://sheets.googleapis.com/v4/spreadsheets/${p.spreadsheet_id}/values/${encodeURIComponent(p.sheet_name)}!A:Z`),r=d.values||[],g=document.querySelector('#projects-grid');document.querySelectorAll('.preview').forEach(x=>x.remove());let e=document.createElement('section');e.className='preview';e.innerHTML=r.length?`<strong>${p.name}</strong><table><thead><tr>${r[0].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.slice(1,11).map(x=>`<tr>${r[0].map((_,i)=>`<td>${x[i]||''}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'Esta hoja no tiene datos.';g.before(e)}catch(e){note(e.message)}}
async function format(p){try{let d=await gf(`https://sheets.googleapis.com/v4/spreadsheets/${p.spreadsheet_id}?fields=sheets.properties`),s=d.sheets.find(x=>x.properties.title===p.sheet_name)||d.sheets[0];await gf(`https://sheets.googleapis.com/v4/spreadsheets/${p.spreadsheet_id}:batchUpdate`,{method:'POST',body:JSON.stringify({requests:[{repeatCell:{range:{sheetId:s.properties.sheetId,startRowIndex:0,endRowIndex:1},cell:{userEnteredFormat:{backgroundColor:{red:.03,green:.48,blue:.44},textFormat:{foregroundColor:{red:1,green:1,blue:1},bold:true}}},fields:'userEnteredFormat(backgroundColor,textFormat)'}}]})});note('Encabezados formateados.')}catch(e){note(e.message)}}
document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();let email=document.querySelector('#email').value,password=document.querySelector('#password').value,r=mode==='signup'?await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await sb.auth.signInWithPassword({email,password});if(r.error)return document.querySelector('#auth-message').textContent=r.error.message;if(mode==='signup'&&!r.data.session)return document.querySelector('#auth-message').textContent='Revisa tu correo y confirma tu cuenta.';ad.close()};
document.querySelector('#close-dialog').onclick=()=>ad.close();document.querySelector('#close-sheet-dialog').onclick=()=>sd.close();document.querySelector('#switch-auth').onclick=()=>modeSet(mode==='login'?'signup':'login');document.querySelector('#authorize-google').onclick=sheets;['#new-project','#connect-sheet'].forEach(x=>document.querySelector(x).onclick=()=>sd.showModal());bind();if(ready()){sb=window.supabase.createClient(cfg.url,cfg.publishableKey);sb.auth.getSession().then(({data})=>data.session&&dashboard(data.session.user));sb.auth.onAuthStateChange((_,s)=>{if(s?.provider_token)token=s.provider_token;if(s?.user)dashboard(s.user)})}
